# Generated by Django 5.2.6 on 2025-09-17 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
            ],
        ),
        migrations.AlterModelOptions(
            name='artifact',
            options={'verbose_name': 'Артифакт', 'verbose_name_plural': 'Артифакты'},
        ),
        migrations.AlterField(
            model_name='artifact',
            name='group_name',
            field=models.TextField(verbose_name='Эпоха'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='museum.group'),
        ),
    ]
