# Generated by Django 5.2.6 on 2025-09-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0002_group_alter_artifact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Эпоха', 'verbose_name_plural': 'Эпохи'},
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='group_name',
        ),
    ]
