# Generated by Django 5.2.6 on 2025-10-22 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0004_exhibition_hall_curator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifact',
            options={'verbose_name': 'Артефакт', 'verbose_name_plural': 'Артефакты'},
        ),
        migrations.RemoveField(
            model_name='curator',
            name='name',
        ),
        migrations.AddField(
            model_name='curator',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibition',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='museum.hall'),
        ),
    ]
