# Generated by Django 5.2.6 on 2025-10-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0005_alter_artifact_options_remove_curator_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='picture',
            field=models.ImageField(null=True, upload_to='museum', verbose_name='Изображение'),
        ),
    ]
