# Generated by Django 5.2.6 on 2025-11-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_artifact_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='halls/'),
        ),
    ]
