# Generated by Django 5.2.6 on 2025-12-10 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0009_remove_group_user_alter_artifact_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id'], 'verbose_name': 'Эпоха', 'verbose_name_plural': 'Эпохи'},
        ),
        migrations.AlterField(
            model_name='artifact',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='picture',
            field=models.ImageField(null=True, upload_to='museum'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curator',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='museum.hall'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hall',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hall',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(null=True)),
                ('stage', models.TextField(null=True)),
                ('type', models.TextField(choices=[('curator', 'смотритель'), ('guide', 'экскурсовод')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
