# Generated by Django 5.2.6 on 2025-12-15 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0011_artifact_created_at_artifact_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_create_artifacts', 'Может создавать экспонаты')]},
        ),
    ]
